version: '3.8'
services:
  api:
    build: .
    restart: unless-stopped
    ports:
      - "8081:8081"
    networks:
      - shared-network
    environment:
      - JWT_SECRET=supersecret
      - EXPIRES_IN=1
      - HOST=postgres
      - PORT=5432
      - USERNAME=postgres
      - PASSWORD=postgres
      - DATABASE=postgres
  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    networks:
      - shared-network

networks:
  shared-network: